store:
  folder: /tmp/elysiandb-2
  shards: 512
  flushIntervalSeconds: 5
  crashRecovery: { enabled: true, maxLogMB: 100 }
server:
  http: { enabled: true,  host: 0.0.0.0, port: 8091 }
  tcp:  { enabled: true,  host: 0.0.0.0, port: 8891 }
log:
  flushIntervalSeconds: 5
stats:
  enabled: false
api:
  index:
    workers: 4
  cache:
    enabled: true
    cleanupIntervalSeconds: 10
